
#---------------------------
# 全局
# Site
#---------------------------
favicon: /img/blog_main_img/icon.png # 网站标签页的 icon

apple_touch_icon: /img/blog_main_img/icon.png # 用于苹果设备的 icon

#---------------------------
# 首页
# Index Page
#---------------------------
index:
  banner_img: https://tva1.sinaimg.cn/large/0082zybpgy1gc5a70mx4jj31f20u0b2a.jpg  # 首页 Banner 头图，以下相同
  banner_img_height: 100  # 头图高度，屏幕百分比，available: 0 - 100
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text:  # 为空则按 hexo config.subtitle 显示
  auto_excerpt:
    enable: true
  post_url_target: _self  # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: true
    tag: true

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100


#---------------------------
# 分类归档页
# Categories Page
#---------------------------
category:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100


#---------------------------
# 标签归档页
# Tags Page
#---------------------------
tag:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  tagcloud: # 标签云
    min_font: 15
    max_font: 30
    unit: px  # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 关于页
# About Page
#---------------------------
about:  # 以下仅为页面顶部的基本信息，更多内容请在 ./pages/about.md 中编辑，支持 markdown 和 HTML
  md_path: ./pages/about.md  # 关于页文档的相对路径，可以按相对文档设置主题之外的路径，从而避免更新冲突
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  avatar: /img/avatar.png # 头像
  name: myname
  introduce: info / info / info # 支持 HTML
  icons: # 更多图标可从 https://fontawesome.com/v5.10.0/icons?d=gallery 查找，并以 "图标名: url" 的格式添加在下方
    "fab fa-github": https://github.com
    "fab fa-twitter": https://twitter.com
    "fab fa-weixin":  # 微信图标，这个是特殊图标，点击不会跳转而是悬浮二维码，所以链接需要对应二维码图片地址


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  subtitle: 'Page not found'


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  items:
    Fluid Docs: [https://hexo.fluid-dev.com/docs/, 主题使用指南]
    Fluid Repo: [https://github.com/fluid-dev/hexo-theme-fluid, 主题 GitHub 仓库]
    Fluid Changelog: [https://github.com/fluid-dev/hexo-theme-fluid/blob/master/Changelog.md, 主题更新日志]